# Generated by Django 4.2.1 on 2023-05-17 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartament_id', models.TextField(default='', unique=True)),
                ('place', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('price', models.FloatField(default=0.0)),
                ('area', models.FloatField(default=0.0)),
                ('price_per_m', models.FloatField(default=0.0)),
                ('rooms', models.TextField(default='')),
                ('offer_url', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment', to_field='apartament_id')),
            ],
        ),
    ]
